spring.application.name=Iot
spring.data.mongodb.uri=mongodb+srv://projetiot:PigZNQGf6lPy97Pk@projetiot.mwwvunz.mongodb.net/BackEndIot?appName=ProjetIot
spring.data.mongodb.database=BackEndIot
# spring.data.mongodb.uri=mongodb://localhost:27017/BackendIot

server.port=8080
server.address=0.0.0.0
jwt.secret=}|a!NZEjrRZ#6Hgwi!>l44}K7ak},z6G^kKn+yB?/SN
jwt.expiration=86400000
mongodb.sensors.uri=${MONGODB_SENSORS_URI:mongodb+srv://projetiot:PigZNQGf6lPy97Pk@projetiot.mwwvunz.mongodb.net/Testing?appName=ProjetIot}

# mongodb.sensors.uri=${MONGODB_SENSORS_URI:mongodb+srv://alex:AQyOblEZsHJZHAtc@sensors.ctflhib.mongodb.net/DataSensor?appName=Sensors"}
# mongodb.sensors.uri=mongodb://localhost:27017/Testing
management.endpoints.web.exposure.include=mappings
management.endpoint.mappings.enabled=true

device.user.id=PU32X7L@.'Q}t,tBV)z]0.3"Mk\v:2ccHY0(qk(@#@#R@v-EK-K@pLi[PSwuk[[{LTr)Eze@}G{iX2x6TS2]p"8)qc=W(Q20R\.066';Mb.E8EX;RLWMciD
allowed.device.id=flask-server
device.secret=x.9xXe+t7LvolRG.Gwz3jwm[,8\j2PRdHFUpJI4'"ux4Y1},\tcc\eum2kPlp[s.L@}{u2I9ZBr"hr!0s0.=7w@#cQG-?1A:*JEf|zO8wwe@pyBKk69p79f
